services:
  kodus-mcp-manager:
    image: ${IMAGE_NAME_PROD}
    container_name: ${CONTAINER_NAME}
    volumes:
      - log_volume:/app/logs
    logging:
      options:
        max-size: "200m"
        max-file: "10"
    ports:
      - "3101:3101"
    environment:
      - NODE_ENV=production
      - API_MCP_MANAGER_NODE_ENV=production
    env_file:
      - .env.prod
    restart: unless-stopped

volumes:
  log_volume:
