FROM node:22.22.0-slim AS development

WORKDIR /app

# Set NODE_ENV to "development"
ENV NODE_ENV=development

# Dependency Installation
COPY package.json yarn.lock ./

# Install system and project dependencies
RUN yarn install

# Copying the application
COPY . .

# Exposing the port
EXPOSE 3101

# Startup command for development
CMD ["yarn", "start:dev"]
