FROM --platform=linux/amd64 node:22.14.0-slim AS development

WORKDIR /usr/src/app

EXPOSE 3101

# Defina a variável de ambiente NODE_ENV para "development"
ENV NODE_ENV=development
ENV API_MCP_MANAGER_NODE_ENV=development

# Copie os arquivos do projeto
COPY package.json yarn.lock ./

# Instale dependências do sistema e do projeto
RUN apt-get update \
    && apt-get install -y --no-install-recommends procps \
    && rm -rf /var/lib/apt/lists/* \
    && yarn install

# Copie o resto dos arquivos
COPY . .

# Comando de inicialização para desenvolvimento
CMD ["yarn", "start:dev"]
