name: Build and Publish Docker Images for Self-Hosted

on:
    release:
        types: [published]

jobs:
    build-and-push:
        name: Build and Push Docker Images for Self-Hosted
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4.2.2

            - name: Capture Release Version
              run: echo "RELEASE_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

            - name: Create .env file with required keys
              run: |
                  [ -f .env ] && rm .env

                  echo API_MCP_MANAGER_PORT=3101 >> .env
                  echo API_MCP_MANAGER_NODE_ENV=production >> .env
                  echo API_MCP_MANAGER_DATABASE_ENV=production >> .env
                  echo API_PG_DB_HOST= >> .env
                  echo API_PG_DB_PORT= >> .env
                  echo API_PG_DB_USERNAME= >> .env
                  echo API_PG_DB_PASSWORD= >> .env
                  echo API_PG_DB_DATABASE= >> .env
                  echo API_MCP_MANAGER_LOG_LEVEL=info >> .env

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3.10.0

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3.4.0
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Docker Metadata
              id: meta
              uses: docker/metadata-action@v5.7.0
              with:
                  images: ghcr.io/${{ github.repository_owner }}/kodus-mcp-manager
                  tags: |
                      type=semver,pattern={{version}}
                      type=raw,value=latest

            - name: Build and Push Docker Images
              uses: docker/build-push-action@v6.15.0
              with:
                  context: .
                  file: ./DockerFiles/Dockerfile.prod
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64,linux/arm64

            - name: Notify Discord on Success
              if: success()
              uses: sarisia/actions-status-discord@v1.15.3
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  content: ':tada: Docker image version `${{ env.RELEASE_VERSION }}` has been successfully built and pushed to GitHub Container Registry (Self-Hosted).'
                  title: 'Build and Push: kodus-mcp-manager (Self-Hosted)'
                  username: 'GitHub Actions'
                  color: 0x00FF00

            - name: Notify Discord on Failure
              if: failure()
              uses: sarisia/actions-status-discord@v1.15.3
              with:
                  webhook: ${{ secrets.DISCORD_WEBHOOK }}
                  content: ':x: Failed to build or push Docker image `${{ env.RELEASE_VERSION }}` to GitHub Container Registry (Self-Hosted). Please check the logs for details.'
                  title: 'Build and Push: kodus-mcp-manager (Self-Hosted)'
                  username: 'GitHub Actions'
                  color: 0xFF0000
